configurations:
    centos-7:
        os: centos
        os_family: linux
        version: 7
        agents:
            build:
                dockerfile: "ci/jenkins/docker/build/centos-7/Dockerfile"
                label: "linux && docker"
                cpack_generator: RPM
                additionalBuildArgs: '--build-arg USER_ID=$(id -u) --build-arg GROUP_ID=$(id -g)'
            test:
              dockerImage: centos:7
    centos-8:
        os: centos
        os_family: linux
        version: 8
        agents:
            build:
                dockerfile: ci/jenkins/docker/build/centos-8/Dockerfile
                label: linux && docker
                cpack_generator: RPM
                additionalBuildArgs: '--build-arg USER_ID=$(id -u) --build-arg GROUP_ID=$(id -g)'
            test:
                dockerImage: centos:8
    fedora-31:
        os: fedora
        os_family: linux
        version: 31
        agents:
            build:
                dockerfile: ci/jenkins/docker/build/fedora-31/Dockerfile
                label: linux && docker
                cpack_generator: RPM
                additionalBuildArgs: '--build-arg USER_ID=$(id -u) --build-arg GROUP_ID=$(id -g)'
            test:
                dockerImage: fedora:31
    ubuntu-16.04:
        os: ubuntu
        os_family: linux
        version: 16.04
        agents:
            build:
                dockerfile: ci/jenkins/docker/build/ubuntu-16.04/Dockerfile
                label: linux && docker
                cpack_generator: DEB
                additionalBuildArgs: '--build-arg USER_ID=$(id -u) --build-arg GROUP_ID=$(id -g)'
            test:
                dockerImage: ubuntu:16.04
    ubuntu-18.04:
        os: ubuntu
        os_family: linux
        version: 18.04
        agents:
            build:
                dockerfile: ci/jenkins/docker/build/ubuntu-18.04/Dockerfile
                label: linux && docker
                cpack_generator: DEB
                additionalBuildArgs: '--build-arg USER_ID=$(id -u) --build-arg GROUP_ID=$(id -g)'
            test:
                dockerImage: ubuntu:18.04
