- centos-7 :
    os: centos
    version: 7
    agents:
      build:
        dockerfile: ci/jenkins/docker/build/centos-7/Dockerfile
- centos-8 :
    os: centos
    version: 8
    agents:
      build:
        dockerfile: ci/jenkins/docker/build/centos-8/Dockerfile
- fedora-31 :
    os: fedora
    version: 31
    agents:
      build:
        dockerfile: ci/jenkins/docker/build/fedora-31/Dockerfile
- ubuntu-16.04 :
    os: ubuntu
    version: 16.04
    agents:
      build:
        dockerfile: ci/jenkins/docker/build/ubuntu-16.04/Dockerfile
- ubuntu-18.04 :
    os: ubuntu
    version: 18.04
    agents:
      build:
        dockerfile: ci/jenkins/docker/build/ubuntu-18.04/Dockerfile
